# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20170622_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='submit_choice',
            new_name='choice',
        ),
    ]
