# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20170622_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='answer',
        ),
    ]
