# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_auto_20170622_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('user_answer', 'user')]),
        ),
    ]
