# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20170630_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={},
        ),
    ]
